name: Continuous integration
on: [push]

jobs:
  test-macos-nixpkgs:
    name: Build & Test - macOS (Nixpkgs)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mount Bazel cache
        uses: actions/cache@v1
        with:
          path: ~/repo-cache
          key: repo-cache-${{ secrets.REPO_CACHE_VERSION }}
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=./nixpkgs/default.nix
      - name: Configure
        run: |
          cat >.bazelrc.local <<EOF
          common --config=ci
          # The configuration `ci-macos-nixpkgs` is currently undefined.
          # Replace `ci-macos` by `ci-macos-nixpkgs` when needed.
          build --config=macos-nixpkgs --config=ci-macos
          EOF
      - name: Check Bazel version
        run: |
          nix-shell --arg docTools false --pure --run .ci/check-bazel-version
      - name: Build & test
        run: |
          # Retry if needed due to network flakiness.
          nix-shell --arg docTools false --pure --run \
          'cmd="bazel fetch @stackage//..."; $cmd || $cmd || $cmd'
          # XXX 2019-01-22 Disable start script checking on Darwin
          # due to a clash between binutils and clang.
          # nix-shell --arg docTools false --pure --run \
          #   './tests/run-start-script.sh --use-nix'
          nix-shell --arg docTools false --pure --run '
          set -euo pipefail
          bazel build //tests:run-tests
          ./bazel-ci-bin/tests/run-tests
          bazel coverage //tests/... --build_tag_filters "coverage-compatible" --test_tag_filters "coverage-compatible" --test_output=all
          '
  test-macos-bindist:
    name: Build & Test - macOS (bindist)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mount Bazel cache
        uses: actions/cache@v1
        with:
          path: ~/repo-cache
          key: repo-cache-${{ secrets.REPO_CACHE_VERSION }}
      - name: Install Bazel
        run: |
          BAZEL_DIR="$(.ci/fetch-bazel-bindist)"
          mv $BAZEL_DIR $HOME/bazel
      - name: Configure
        run: |
          cat >.bazelrc.local <<EOF
          common --config=ci
          build --config=macos-bindist --config=ci-macos-bindist --config=ci-macos
          EOF
      - name: Build & test
        run: |
          export BAZEL_USE_CPP_ONLY_TOOLCHAIN=1
          export PATH=$HOME/bazel:$PATH
          # Retry if needed due to network flakiness.
          cmd="bazel fetch @stackage//..."; $cmd || $cmd || $cmd
          # XXX 2019-01-22 Disable start script checking on Darwin
          # due to a clash between binutils and clang.
          # ./tests/run-start-script.sh --use-bindists
          bazel test //tests/...
          # Test stack_snapshot pinning
          # NOTE keep in sync with tests/RunTests.hs
          bazel run @stackage-pinning-test-unpinned//:pin
          bazel build @stackage-pinning-test//:hspec
